VCityTeam/py3dtilers

py3dtilers/GeojsonTiler/GeojsonTiler.py, py3dtilers/GeojsonTiler/README.md, py3dtilers/GeojsonTiler/geojson.py, tests/geojson_tiler_test_data/roads/line_string_road.geojson, tests/geojson_tiler_test_data/roads/multi_line_string_road.geojson, tests/test_geojsonTiler.py
GeojsonTiler can create 3DTiles from LineString and MultiLineString by buffering those lines into polygons.
This PR implements:
* Line buffering
* Custom triangulation method for buffered lines
* Width as argument to use an arbitrary offset value when buffering lines
* Tests for LineString and MultiLineStrings
* Doc update
=> GeojsonTiler can parse LineString and MultiLineString

py3dtilers/CityTiler/CityTemporalTiler.py, py3dtilers/CityTiler/CityTiler.py, py3dtilers/CityTiler/README.md
CityTiler and CityTemporalTiler now use the same `--db_config_path` flag. This avoids conflicts between `db_config_path` from the CityTiler and `--db_config_path` from the CityTemporalTiler. See [issue](https://github.com/VCityTeam/py3dtilers/issues/30)
=> CityTiler and CityTemporalTiler use the same config path

py3dtilers/Common/group.py, py3dtilers/Common/object_to_tile.py, py3dtilers/Common/tileset_creation.py, py3dtilers/GeojsonTiler/GeojsonTiler.py, py3dtilers/GeojsonTiler/README.md, py3dtilers/GeojsonTiler/geojson.py, tests/test_geojsonTiler.py
Store materials in ObjectsToTile. The materials are written into the GlTF during tileset creation.
Create a new flag `--add_color` for the GeojsonTiler. This flag add colors to the features depending on their height (lerp between green and red)
=> Materials in ObjectsToTile & color with GeoJsonTiler

py3dtilers/CityTiler/CityTiler.py, py3dtilers/CityTiler/citym_bridge.py, py3dtilers/CityTiler/citym_building.py, py3dtilers/CityTiler/citym_cityobject.py, py3dtilers/CityTiler/citym_relief.py, py3dtilers/CityTiler/citym_waterbody.py
CityTiler used to load all texture images during [the geometry creation](https://github.com/VCityTeam/py3dtilers/blob/master/py3dtilers/CityTiler/CityTiler.py#L89) (images of the __whole tileset__ were loaded in memory). The Tiler memory usage was going up to __9 Go__ (28% of 32 Go RAM) for Lyon 1st borough.
With this PR, the textures are loaded tile by tile during the [atlas creation](https://github.com/VCityTeam/py3dtilers/blob/master/py3dtilers/Texture/atlas.py#L17). This way, the Tiler memory usage only goes up to __0,65 GO__ (0,5 GO on average) for the same borough.
The computation time stay the same.
=> Optimize texture memory in CityTiler 

py3dtilers/CityTiler/CityTiler.py, py3dtilers/CityTiler/README.md, py3dtilers/CityTiler/citym_cityobject.py, py3dtilers/CityTiler/citym_waterbody.py, py3dtilers/Common/object_to_tile.py, py3dtilers/ObjTiler/obj.py, py3dtilers/Texture/atlas.py, py3dtilers/Texture/texture.py
Create textured 3DTiles of relief, water bdies and bridges (see [issue](https://github.com/VCityTeam/py3dtilers/issues/43)). The main problem seemed to be in our 3DTiles viewer [UD-Viz](https://github.com/VCityTeam/UD-Viz) and was fixed in [this PR](https://github.com/VCityTeam/UD-Viz/pull/275).
This PR reduce the computation time of textured 3DTiles with the CityTiler.
- Choose the object type (buildings, relief, etc) with `--type` flag
- Add textures to water bodies
- Query texture images only once per tile. We used to query the same image a lot of time when many surfaces shared a texture
=> Textures for relief/bridges/waterbodies in CityTiler

py3dtilers/CityTiler/CityTiler.py, py3dtilers/CityTiler/citym_bridge.py, py3dtilers/CityTiler/citym_building.py, py3dtilers/CityTiler/citym_cityobject.py, py3dtilers/CityTiler/citym_relief.py, py3dtilers/CityTiler/citym_waterbody.py
Remove the cityobject envelope from 3D City DB city objects query since it is not used at this stage. The envelope is computed later on, from the geometries, in the `get_surfaces_...` methods of the CityTiler, e.g. [here](https://github.com/VCityTeam/py3dtilers/blob/master/py3dtilers/CityTiler/CityTiler.py#L56).
Subsequently, don't drop city objects that don't have an envelope in the database.
=> [CityTiler] don't drop city objects that don't have an envelope in database

py3dtilers/TilesetReader/TilesetMerger.py
Texture images can be stored inside the JSON of the gltf (as opposed to externally in a jpg or png file), see [this part of the spec](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#images). This PR manages this case by not trying to move images that don't have a `uri` attribute in the gltf header and avoids the tileset-merger to break in these cases.
=> Tileset-merger: manage "in-gltf" images 

py3dtilers/CityTiler/CityTemporalTiler.py, py3dtilers/CityTiler/CityTiler.py, py3dtilers/CityTiler/citym_cityobject.py, py3dtilers/CityTiler/temporal_building.py, py3dtilers/Common/__init__.py, py3dtilers/Common/feature.py, py3dtilers/Common/geometry_node.py, py3dtilers/Common/group.py, py3dtilers/Common/lod_feature_list.py, py3dtilers/Common/lod_node.py, py3dtilers/Common/lod_tree.py, py3dtilers/Common/polygon_extrusion.py, py3dtilers/Common/tiler.py, py3dtilers/Common/tileset_creation.py, py3dtilers/GeojsonTiler/GeojsonTiler.py, py3dtilers/IfcTiler/IfcTiler.py, py3dtilers/ObjTiler/ObjTiler.py, py3dtilers/TilesetReader/TilesetMerger.py, py3dtilers/TilesetReader/TilesetReader.py, tests/test_cityTemporalTiler.py, tests/test_cityTiler.py, tests/test_geojsonTiler.py, tests/test_objTiler.py, tests/test_tiler.py, tests/test_tilesetReader.py
Create and write the tileset tile by tile. Each tile is transformed (reprojected, translated, etc) separately. Once a tile is created, its content (.b3dm) is writen on the disk and deleted from the memory.
Also, the CityTiler now loads the geometries of the features tile by tile. The distribution of the features into tiles can be done with only the centroid of each feature. When dealing with huge amount of data, loading only the triangles of the current tile drastically reduce the memory usage.
This PR also comes with a rework of the LODs creation. The objectives were to:
- Create the LODs tile by tile (and not before the tileset creation)
- Clarify the LOA creation
See [issue](https://github.com/VCityTeam/py3dtilers/issues/58) for more details
_Note_: py3dtiles needs to be uninstalled …
=> Create and write tileset tile by tile

py3dtilers/CityTiler/CityTiler.py, py3dtilers/Common/README.md, py3dtilers/Common/kd_tree.py, py3dtilers/Common/tiler.py, tests/test_cityTemporalTiler.py, tests/test_cityTiler.py, tests/test_geojsonTiler.py, tests/test_objTiler.py, tests/test_tiler.py, tests/test_tilesetReader.py
New `--kd_tree_max` to set the maximum number of features in each tile when the features are distributed with a kd-tree. The flag must be followed by an integer.
Example:
```bash
citygml-tiler --type building --kd_tree_max 25  # Each tile while contain a maximum of 25 buildings 
```
Create a `DEFAULT_KD_TREE_MAX` equal to 500 and used when the user has not specified a value. When using the CityTiler with texture, this default value is divided by 20 to reduce the size of each image atlas (--> since there is one atlas by tile, if the tile contains to much features, the atlas will be too heavy).
[Issue](https://github.com/VCityTeam/py3dtilers/issues/76)
=> Set kd-tree max in command line

py3dtilers/Common/feature.py
We now let Py3DTiles ensure that the created geometry of tiles are in float32.
All computations in py3dtilers can be made with float64 to avoid approximation and artefact.
/!\ Need to accept this [pr](https://github.com/VCityTeam/py3dtiles/pull/23) on Py3DTiles and reinstall Py3DTiles to ensure this PR to work properly
=> Fix Translation

py3dtilers/GeojsonTiler/GeojsonTiler.py, py3dtilers/GeojsonTiler/README.md, tests/test_geojsonTiler.py
You can use the flag `-k` or `--keep_properties` to store the properties of the GeoJSON features in the batch table. All the properties of each feature will be stored.
```bash
geojson-tiler --path <path> --keep_properties
```
As shown below, this allows to visualize the properties of each building
=> [GeojsonTiler] Allows to keep GeoJSON features properties in the Batch Table

py3dtilers/CityTiler/CityTiler.py, py3dtilers/CityTiler/README.md, py3dtilers/Common/README.md, py3dtilers/Common/tiler.py, py3dtilers/GeojsonTiler/GeojsonTiler.py, py3dtilers/GeojsonTiler/README.md, py3dtilers/IfcTiler/IfcTiler.py, py3dtilers/IfcTiler/README.md, py3dtilers/ObjTiler/ObjTiler.py, py3dtilers/ObjTiler/README.md, py3dtilers/ObjTiler/obj.py, py3dtilers/TilesetReader/README.md, py3dtilers/TilesetReader/TilesetMerger.py, py3dtilers/TilesetReader/TilesetReader.py, tests/test_geojsonTiler.py, tests/test_ifcTiler.py, tests/test_objTiler.py, tests/test_tilesetReader.py
This PR introduce a common input mechanism shared by all the tilers.
The tilers now use the `-i` for the input. The flag should be followed by at least one path. Each path should point to a file or a directory holding a set of files.
Note that the old input flags (`--path`, `--paths`, `--db_config_file`, `--file_path`) were kept as alternatives of `-i` to ensure retro-compability.
=> Common input mechanism for all the tilers

py3dtilers/Common/README.md, py3dtilers/Common/geometry_node.py, py3dtilers/Common/lod_tree.py, py3dtilers/Common/tiler.py, py3dtilers/Common/tileset_creation.py, py3dtilers/Texture/atlas.py, py3dtilers/Texture/atlas_node.py, tests/test_cityTemporalTiler.py, tests/test_cityTiler.py, tests/test_geojsonTiler.py, tests/test_ifcTiler.py, tests/test_objTiler.py, tests/test_tiler.py, tests/test_tilesetReader.py
The flag `--texture_lods` (or `--tl`) can be used to set the number of levels of detail that will be created for each textured tile. Each level of detail will be a tile with a less detailled image but the same geometry. The size of the images is reduced with a [Nearest Neighbor Resampling algorithm](https://clouard.users.greyc.fr/Pantheon/experiments/rescaling/index-en.html#nearest).
```bash
<tiler> <input> --texture_lods 4  # Create 4 additional tiles for each textured tile
```
The first additional level has downsize ratio of 3, meaning the image will be 3 times smaller than the original. Then each following level increment this ratio by 10.
```mermaid
graph TD;
LOD1[LOD1, ratio=33];
LOD2[LOD2, ratio=23];
LOD3[LOD3, ratio=13];
LOD4[LOD4, ratio=3];
Tile[Textured …
```
=> Create texture levels of detail

py3dtilers/CityTiler/CityTiler.py, py3dtilers/CityTiler/README.md, py3dtilers/CityTiler/citym_bridge.py, py3dtilers/CityTiler/citym_building.py, py3dtilers/CityTiler/citym_cityobject.py, py3dtilers/CityTiler/citym_relief.py, py3dtilers/CityTiler/citym_waterbody.py, py3dtilers/Common/README.md, py3dtilers/Common/feature.py, py3dtilers/Common/tiler.py, tests/test_cityTemporalTiler.py, tests/test_cityTiler.py, tests/test_geojsonTiler.py, tests/test_ifcTiler.py, tests/test_objTiler.py, tests/test_tiler.py
- New IDs filter mechanism working for all tilers (except the IFC tiler).
- Allows to keep or exclude features
- The flag `--ids` of the CityTiler is deleted. With the CityTiler, we use the CityGML ID (instead of the database ID) to filter.
Usage:
The flag `--keep_ids` and `--exclude_ids` allows to filter the features. The flag must be followed by a list of IDs.
`--keep_ids` keeps **only** the features which have their ID in the list.
```bash
<tiler> <input> --keep_ids id_1 id_2  # Keep only the features with those IDs
```
`--exclude_ids` **exclude** the features which have their ID in the list.
```bash
<tiler> <input> --exclude_ids id_1 id_2  # Exclude the features with those IDs
```
=> Keep and exclude IDs in all tilers

py3dtilers/CityTiler/citym_cityobject.py, py3dtilers/Common/feature.py, py3dtilers/Common/tileset_creation.py
When creating 3DTiles from CityGML data with split surfaces (`--split_surfaces`), save the surface classname as an attribute in the bath table
- new method to add data in the batch table data of a feature
- save surface classname as `citygml::surface_type` in the batch table
=> Add CityGML surface type in batch table

py3dtilers/__init__.py
Fix py3DTilers version in __init__.py file.
Issue link : https://github.com/VCityTeam/py3dtilers/issues/152
=> Fix incorrect py3DTilers versions in __init__.py

py3dtilers/Common/tiler.py, py3dtilers/TilesetReader/TilesetMerger.py
I fix the issue by replacing `parse_args` function by `parse_known_args` ; https://github.com/VCityTeam/py3dtilers/issues/155.
=> Replace parse_args function by parse_known_args

py3dtilers/Common/README.md, py3dtilers/Common/tiler.py, py3dtilers/Common/tileset_creation.py, tests/test_cityTemporalTiler.py, tests/test_cityTiler.py, tests/test_geojsonTiler.py, tests/test_ifcTiler.py, tests/test_objTiler.py, tests/test_tiler.py
This option is very useful for tiles created out of Photogrammetry datasets.
=> Added new "--no_normals" option to not include normals in 3D tiles

.travis.yml, py3dtilers/Common/feature.py, py3dtilers/Common/tiler.py, py3dtilers/Common/tileset_creation.py
There are two important changes here that I think are necessary:
1. I think we should first add offset to coordinates and then do a transform. Existing code does it differently: it separately transforms an offset and vertices. Depending on the projection, you might get different results.
2. In tileset_creation on line 70 I am not adding centroid value. In OBJ meshes that I have (generated in Pix4d) all coordinates in the mesh can be converted to projection coordinates by adding offset values. If this changes causes issues with other datasets, we can implement this as an option on crs reprojection.
=> Mesh reprojection changes

py3dtilers/Texture/atlas.py, py3dtilers/Texture/atlas_node.py
Create texture atlases whose size is a power of 2
Texture images are slightly larger on disk (~1.07 time larger than before) but will be rendered more quickly (see #170 and [NPOT textures](https://www.soft8soft.com/wiki/index.php/NPOT_Textures#:~:text=An%20NPOT%20texture%20is%20a,Power%2DOf%2DTwo))
=> POT texture

.travis.yml, LICENSE.md, README.md, setup.py
Clean requirements to support at least Python 3.9 and 3.10. Yet to test with >=3.11, not sure we should support <3.8
TODO:
=> Support for Python 3.8, 3.10 & 3.11

py3dtilers/GeojsonTiler/geojson.py, py3dtilers/GeojsonTiler/geojson_line.py, py3dtilers/GeojsonTiler/geojson_polygon.py, setup.py
That PR addresses issue https://github.com/VCityTeam/py3dtilers/issues/64 by adding to geojsontiler support for interior rings.
=> feat(geojsontiler): add interior rings support

tests/test_ifcTiler.py
Since the test is failing on Unix systems due to IfcOpenShell, allows the test to fail
=> test: allow IfcTiler test to fail

CONTRIBUTORS.md
That PR updates the contributors file to include those who contributed to the previous PR https://github.com/VCityTeam/py3dtilers/pull/180.
=> chore: update contributors
